apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberdeploys
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kuberdeploys
  template:
    metadata:
      labels:
        app: kuberdeploys
    spec:
      containers:
        - name: kuberdeploys
          image: kiranboppana/k8sdeploy
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kuberdeploys
spec:
  selector:
    app: kuberdeploys
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
